steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/gitlab-status-bot:$COMMIT_SHA', '.']
  
  # Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/gitlab-status-bot:$COMMIT_SHA']
  
  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'gitlab-status-bot'
    - '--image=gcr.io/$PROJECT_ID/gitlab-status-bot:$COMMIT_SHA'
    - '--region=us-central1'
    - '--platform=managed'
    - '--allow-unauthenticated'
    - '--port=3000'
    - '--min-instances=0'        # Scale to zero when idle
    - '--max-instances=3'        # Limit concurrent instances
    - '--concurrency=80'         # Handle multiple requests per instance
    - '--cpu=1'                  # Minimal CPU
    - '--memory=512Mi'           # Minimal memory
    - '--timeout=300'            # 5 minutes max (for long GitLab API calls)
    - '--set-env-vars=NODE_ENV=production'

# Store the built image
images:
- 'gcr.io/$PROJECT_ID/gitlab-status-bot:$COMMIT_SHA'

# Specify build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'  # Faster builds 